### ISSUE TITLE
Collect statistics by groups of queries

### ISSUE THREAD

**Issue by munakoiso** [powa-team/pg_stat_kcache#30]
Hi!
I made a patched version of pg_stat_kcache (on behalf of Yandex.Cloud). We think that added functionality can be useful for other users. Therefore, it would be great if it appeared in this repository as well. How do you look at it?

The patch allows you to collect statistics on groups of requests, which are determined by the user. Groups are formed as sets of unique key-value pairs that the user specifies in the comment line in the request.

We use this functionality to search for users who create the anomalous load on a certain resources.

Example:
The database receives requests of the form
```
/* sql: {name_of_sql_query} request_id: {request_id} bucket: {name_of_bucket} */ {some_sql_query};
```
In this case, we are only interested in statistics on sql and bucket, so we add the request_id key to the exceptions in advance.

So we can find out what type of requests was called most often over the entire interval of collecting statistics (in this configuration - one day) 
```
> select * from pgsk_get_stats() order by query_count desc limit 1;
NOTICE:  00000: pgsk: Show stats from '2021-04-08 13:35:22.532476+03' to '2021-04-09 13:42:53.853272+03'
LOCATION:  pgsk_internal_get_stats_time_interval, pgsk_aggregated_stats.c:735
-[ RECORD 1 ]+----------------------------------------------
comment_keys | {"sql": "drop_object", "bucket": "f-web"}
query_count  | 43264
userid       | 16394
dbid         | 16607
reads        | 0
writes       | 0
user_time    | 2.081037999999943
system_time  | 0.1518120000000021
minflts      | 1101
majflts      | 0
nswaps       | 0
msgsnds      | 0
msgrcvs      | 0
nsignals     | 0
nvcsws       | 24
nivcsws      | 13
in_network   | 13791440
out_network  | 5883904

Time: 4.134 ms
```
Or, for example, the top by execution time in the last two hours 
```
> select comment_keys, system_time from pgsk_get_stats_time_interval(current_timestamp - '2h'::interval, current_timestamp) order by system_time desc limit 3;
NOTICE:  00000: pgsk: Show stats from '2021-04-09 11:40:10.532476+03' to '2021-04-09 13:44:33.7397+03'
LOCATION:  pgsk_internal_get_stats_time_interval, pgsk_aggregated_stats.c:735
                            comment_keys                            |      system_time      
--------------------------------------------------------------------+-----------------------
 {"sql": "list_objects_experiment", "bucket": "mct"}            |              0.040639
 {"sql": "list_objects", "bucket": "s-compile"}                 | 0.0044680000000000275
 {"sql": "add_chunk", "bucket": "s3-test-acceptance-j8l8lx05d2-31"} | 0.0011609999999999954
(3 rows)

Time: 2.481 ms
```

In the postgres config file you can configure the amount of memory allocated for this statistics, the duration of interval for collecting statistics and add exceptions for keys.

**Comment by rjuju** [comment]
Hi!

I'm not sure I understand everything yet.  If I understand correctly, you have some additional code to be able to track some information from comments (I assume similarly to pg_hint_plans), extract some some information from there if it matches something like `((\w+):  {(\w+)})*` and store the pairs of (key, value) extracted from that with the entries, is that correct?

Are those part of the key, if not are you assuming that a single (userid, dbid, queryid) won't change the comments, or it it does will you keep the first or last one saw?

Then on top of that it seems that you have an additional shmem area where you can store some history.  Is it stored in another hash table or some ring buffer?  Do you store entries there or only the keys?

Finally, it also seem that you track the network activity (in_network and out_network), which is a really good idea.  What are you using to get this information, and how portable is that?

**Comment by munakoiso** [comment]
> I'm not sure I understand everything yet. If I understand correctly, you have some additional code to be able to track some information from comments (I assume similarly to pg_hint_plans), extract some some information from there if it matches something like ((\w+): {(\w+)})* and store the pairs of (key, value) extracted from that with the entries, is that correct?

Yes, it's correct.

>Are those part of the key, if not are you assuming that a single (userid, dbid, queryid) won't change the comments, or it it does will you keep the first or last one saw?

Not sure i understand this question.
Userid, dbid is the part of key in hash table. For every query with specific set of key-value pairs from comment string, and specific userid, dbid i add query stats to entry in hash table.

> Is it stored in another hash table or some ring buffer? Do you store entries there or only the keys?

Every unique key (keys-value pairs from comment + userid + dbid) stored in ring buffer. Entries with stats stored in hash table.

> Finally, it also seem that you track the network activity (in_network and out_network), which is a really good idea. What are you using to get this information, and how portable is that?

In_network is approximated by size of query, out_network is approximated by TupleDescSize * number_of_tuples. Not sure if this is very accurate, but i think it's better than nothing.

**Comment by rjuju** [comment]
> Userid, dbid is the part of key in hash table. For every query with specific set of key-value pairs from comment string, and specific userid, dbid i add query stats to entry in hash table.

So the key-value comments are part of the entry?  What happens if they change in the comments?  How do you handle the memory allocation for those, using standard shmem or dsa?

> Every unique key (keys-value pairs from comment + userid + dbid) stored in ring buffer. Entries with stats stored in hash table.

Ok, so you can see what queries were executed on a specified interval, but you can't know how much resources were consumed right?

> In_network is approximated by size of query, out_network is approximated by TupleDescSize * number_of_tuples. Not sure if this is very accurate, but i think it's better than nothing.

Ah I see.  I'm wondering if you can get really wrong results this way, for instance if you have cursors that you don't read entirely.

**Comment by munakoiso** [comment]
> So the key-value comments are part of the entry?

I think we need more details here. 
First few (now 5) keys from comments keep in some list (the rest keys will be ignored). Each value(=string) from comment is stored in hash table (dictionary from strings to self-created id's).
Then, each comment can be stored as set of id's of values from comment.
For example:
Queries:
```
/* key1: value1*/ ...;
/* key2: value2*/ ...;
/* key2: value3 key1: value2*/ ...;
```
List of keys after these queries:
```[key1, key2, null, null, null]```

dictionary string->id _(there is also a reverse hash table id->string)_:
```
value1: some_id_1
value2: some_id_2
value3: some_id_3
```

sets of value id's, that represents each comment:
```
 [some_id_1, null     , null, null, null]
 [null     , some_id_2, null, null, null]
 [some_id_2, some_id_3, null, null, null]
```

Counters hash table looks like:
```
Key {
set of value id's (like above)
dbid
userid
id of bucket (ring buffer is devided into buckets to make possible stat collecting by time)
}

Value {
Key (should be here because of hash table structure)
pgskCounters
}
```
Well, yes, key-value comments is a part of value. But only because of hash table structure.


>  What happens if they change in the comments?

As you can see above, we can change structure of comment in each query. Previous stats will be kept.

> How do you handle the memory allocation for those, using standard shmem or dsa?

I use standard shmem.

>  but you can't know how much resources were consumed right?

In pgsk_ExecutorEnd i use function like pgsk_entry_store to store counters into a hash table.

**Comment by rjuju** [comment]
Thanks for the extra details.

I think that the comment_keys part should be done inside a distinct extension.  It doesn't really need to be part of pgsk as it's a more general infrastructure, and it can also be useful with other extensions too as it's associating the key-value comments to some (userid, dbid, queryid)  keys.  If you have a dedicated extension you could apply this tagging to pg_stat_statements, pg_stat_kcache and any other extension that tracks counters based on the queryid.

The ring buffer part is quite nice, but it would also be a shame if it was only available for pg_stat_kcache and no other extensions.  There's at least one person interested in having a similar feature for pg_stat_statements, so I'm wondering whether it could be implemented in an extensible way.  Maybe some library offering the generic infrastructure letting third-party extensions use it storing their own data?

**Comment by munakoiso** [comment]
> Maybe some library offering the generic infrastructure letting third-party extensions use it storing their own data?

Sounds great. I will deal with this in the near future.
