### ISSUE TITLE
unknown type name «LWLock»

### ISSUE THREAD

**Issue by extense1337** [powa-team/pg_stat_kcache#37]
OS: Centos 7
DB: PostgreSQL 12

Hi! I am getting error while trying to compile extension. Installed pg_config from postgresql-devel.
When I do "make", C errors occur. Compiler can't find type LWLock, and then it tells that function arguments does not match.
Command line:
```
[admin@localhost pg_stat_kcache-REL2_2_1]$ make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pg_stat_kcache.o pg_stat_kcache.c
pg_stat_kcache.c:130:2: ошибка: unknown type name «LWLock»
  LWLock    *lock;     /* protects hashtable search/modification */
  ^
...
...
pg_stat_kcache.c:1297:2: ошибка: несовместимый тип аргумента 1 функции «LWLockRelease»
  LWLockRelease(pgsk->lock);

  ^
In file included from /usr/include/pgsql/server/storage/lock.h:18:0,
                 from /usr/include/pgsql/server/access/genam.h:20,
                 from /usr/include/pgsql/server/access/hash.h:20,
                 from pg_stat_kcache.c:29:
/usr/include/pgsql/server/storage/lwlock.h:112:13: замечание: expected «LWLockId» but argument is of type «int *»
 extern void LWLockRelease(LWLockId lockid);
             ^
make: *** [pg_stat_kcache.o] Ошибка 1
```

Attached two files, full text of make errors and pg_config.

[make_error.txt](https://github.com/powa-team/pg_stat_kcache/files/10909353/make_error.txt)
[pg_config.txt](https://github.com/powa-team/pg_stat_kcache/files/10909354/pg_config.txt)

**Comment by rjuju** [comment]
Unfortunately It's hard to help with that few information, I don't know which command you used, how you installed postgres, in which path the packages installed stuff and so on.

Note that the extension is available in compiled form through the PGDG repository at https://yum.postgresql.org/, although I'm not sure it would play well if you installed postgres from the centos repository.

**Comment by extense1337** [comment]
I installed PG from the offical repo [(repo)](https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm), before that excluding from centos repo. PG server exactly 12 version. But thank's you for the information! I'll try to figure it out. If I solve the problem, I'll let you know. Probably postgresql-devel should be excluded from centos repos too. In general, you can close the issue.

**Comment by extense1337** [comment]
For some reason, the PATH for pg_config was not set by default. I added it manually now everything works.

**Comment by rjuju** [comment]
Great news, thanks for the confirmation.

Note that since you're installing postgres from the PGDG repository, it's recommended to get the packaged version of pg_stat_kcache there too, with a simple yum / dnf install rather than compiling it yourself.

**Comment by extense1337** [comment]
Yeap, it was much easier to just install compiled from repo. Unfortunately, I didnt found this the first time. Now I do only yum install, thank you!
```
sudo yum install pg_stat_kcache_12
```
